#!/usr/bin/env python2
#
# New arccjobs command that can summarize running jobs
# in specialized orders like strictly user, account only
# qos breakdown, etc. 
#
# NOTE: There seems to be quite a bit of code repeated since
# I started suggesting that I could do this better here. 
#
#
# Thoughts:
#   -   To implement the json, it might be easier to just use basic Python
#       data structures to avoid other issues. I'm not sure how well a
#       nested json output might behave.
#   -   Might need an exception block when getting terminal dims if this
#       provides web stuff
#   -   Nested structures for au qa qu qau outputs
#

#
# Import necessary modules
#
import sys,os
from pwd import getpwnam,getpwuid
import time
import argparse

import pyslurm

# Global Variables
CLUSTER="Slurm"
DEBUG=0


# Get the current time
CURR_TIME = int(time.time())

# Get console dims
def terminal_size():
    import fcntl, termios, struct
    h, w, hp, wp = struct.unpack('HHHH',
        fcntl.ioctl(0, termios.TIOCGWINSZ,
        struct.pack('HHHH', 0, 0, 0, 0)))
    return w, h
CONS_WIDTH,CONS_HEIGHT = terminal_size()
CONS_WIDTH -= 1

# Some wrapper utilities
def Print(xstring):
    sys.stdout.write(str(xstring) + '\n')
    return 0

def PrintWarn(xstring):
    if 0 < DEBUG:
        sys.stderr.write("WARNING: msg\n".format(msg=xstring))

def PrintError(xstring):
    if 0 < DEBUG:
        sys.stderr.write("ERROR: " + str(xstring) + '\n')

def PrintDebug(xstring,debug=0):
    if debug <= DEBUG:
        sys.stderr.write("DEBUG[{lvl}]: {msg}\n".format(lvl=debug,msg=str(xstring)))

def check_state(state):
    if state in ["cancelled","completed","failed","timeout"]: 
        PrintWarn("Job has state {state}".format(state=state))
        return False
    return True

# Basic "summary" class for holding the necessary data
class JobsSummary(object):
    def __init__(self):
        self.njobs = {"pending":0,"running":0,"completed":0,"completing":0}
        self.ncpus = {"pending":0,"running":0,"completed":0,"completing":0}
        self.wtime = {"pending":0.0,"running":0.0,"completed":0.0,"completing":0.0}

    def addJob(self,state,ncpus,wtime):
        k = state
        self.njobs[k] += 1
        self.ncpus[k] += ncpus
        self.wtime[k] += wtime # Can be pending or running
        return None

    def pprint(self):
        print(self.njobs)
        print(self.ncpus)
        print(self.wtime)
        return None

    def __str__(self):
        x = "{rjobs:5d} {rcpus:8d} {rtime:11.2f} {pjobs:5d} {pcpus:8d} {ptime:11.2f}".format(
                rjobs=self.njobs["running"], rcpus=self.ncpus["running"], rtime=self.wtime["running"],
                pjobs=self.njobs["pending"], pcpus=self.ncpus["pending"], ptime=self.wtime["pending"] )
        return x

def printHeader(title="blah"):
    Print(CONS_WIDTH*'-')
    Print(title.center(CONS_WIDTH,' '))
    Print(CONS_WIDTH*'-')

def printTotals(total_string = "blah"):
    Print(CONS_WIDTH*'-')
    Print(total_string)
    Print(CONS_WIDTH*'-')

def printTableHeader(main="Entity",submain="",subsubmain=""):
    if "" == submain:
        x = "{entity:22s} {rjobs:>5s} {rcpus:>8s} {rtime:>11s} {pjobs:>5s} {pcpus:>8s} {ptime:>11s}".format(
            entity=main, 
            rjobs="rjobs", rcpus="rcpus", rtime="rcpuh", 
            pjobs="pjobs", pcpus="pcpus", ptime="pcpuh"  )
    elif "" == subsubmain:
        x  = "{entity:22s}\n ".format(entity=main)
        x += "{subent:21s} {rjobs:>5s} {rcpus:>8s} {rtime:>11s} {pjobs:>5s} {pcpus:>8s} {ptime:>11s}".format(
                subent=submain,
                rjobs="rjobs", rcpus="rcpus", rtime="rcpuh",
                pjobs="pjobs", pcpus="pcpus", ptime="pcpuh"  )
    else:
        x  = "{entity:22s}\n {subent:21s}\n  ".format(entity=main,subent=submain)
        x += "{ssubent:20s} {rjobs:>5s} {rcpus:>8s} {rtime:>11s} {pjobs:>5s} {pcpus:>8s} {ptime:>11s}".format(
                ssubent=subsubmain,
                rjobs="rjobs", rcpus="rcpus", rtime="rcpuh",
                pjobs="pjobs", pcpus="pcpus", ptime="pcpuh"  )


    Print(x)
    Print(CONS_WIDTH*'-')

# This can no be renamed the user summary :)
def userSummary(json=False):

    cluster = JobsSummary()

    user_summary = {}
    users = {};

    jobs = pyslurm.job().get()
    for id,job in jobs.iteritems():
        state = job["job_state"].lower()
        if not check_state(state):
            continue
        ncpus = job["num_cpus"]
        if state == "pending":
            # Warning: time_limit stored in minutes
            wtime = float( job["time_limit"] ) / 60.0
        elif state == "running":
            wtime = float( CURR_TIME - job["start_time"] ) / 3600.0
        wtime *= float(ncpus)

        userid = job["user_id"]
        if userid not in users.keys():
            users[userid] = getpwuid(userid)[0]
            user_summary[users[userid]] = JobsSummary()
       
        user_summary[users[userid]].addJob(
                state,ncpus,wtime
                )

        cluster.addJob(
            state,ncpus,wtime
            )
    printHeader(title="{cluster} User Job Summary".format(cluster=CLUSTER))
    printTableHeader(main="User")
    for k,v in sorted(user_summary.iteritems()):
        Print("{user:22s} {data}".format(user=k,data=str(v)))
    printTotals(total_string = "{summary:22s} {data}".format(summary="TOTAL",data=str(cluster)))

    return 0

def acctSummary(json=False):

    cluster = JobsSummary()

    acct_summary = {}
    
    jobs = pyslurm.job().get()
    for id,job in jobs.iteritems():
        state = job["job_state"].lower()
        if not check_state(state):
            continue
        ncpus = job["num_cpus"]
        if "pending" == state:
            wtime = float( job["time_limit"] ) / 60.0
        elif state == "running":
            wtime = float( CURR_TIME - job["start_time"] ) / 3600.0
        wtime *= float(ncpus)
        acct = job["account"]
        if acct not in acct_summary.keys():
            acct_summary[acct] = JobsSummary()
        acct_summary[acct].addJob( state, ncpus, wtime )

        cluster.addJob( state, ncpus, wtime )

    printHeader(title="{cluster} Account Job Summary".format(cluster=CLUSTER))
    printTableHeader(main="Account")
    for k,v in sorted(acct_summary.iteritems()):
        Print("{acct:22s} {data}".format(acct=k,data=str(v)))
    printTotals(total_string = "{summary:22s} {data}".format(summary="TOTAL",data=str(cluster)))
    return 0

def qosSummary(json=False):

    cluster = JobsSummary()
    
    qos_summary = {}

    jobs = pyslurm.job().get()
    for id,job in jobs.iteritems():
        state = job["job_state"].lower()
        if not check_state(state):
            continue
        ncpus = job["num_cpus"]
        if "pending" == state:
            wtime = float( job["time_limit"] ) / 60.0
        elif "running" == state:
            wtime = float( CURR_TIME - job["start_time"] ) / 3600.0
        wtime *= float( ncpus )
        qos = job["qos"]
        if qos not in qos_summary.keys():
            qos_summary[qos] = JobsSummary()
        qos_summary[qos].addJob( state, ncpus, wtime )

        cluster.addJob( state, ncpus, wtime )

    printHeader(title="{cluster} QoS Job Summary".format(cluster=CLUSTER))
    printTableHeader(main="QoS")
    for k,v in sorted(qos_summary.iteritems()):
        print("{qos:22s} {data}".format(qos=k,data=str(v)))
    printTotals(total_string = "{summary:22s} {data}".format(summary="TOTAL",data=str(cluster)))
    return 0

def auSummary(json=False):

    printHeader(title="{cluster} Account / User Job Summary".format(cluster=CLUSTER))
    printTableHeader(main="Account",submain="User")
    print ""
    printTotals(total_string = "{summary:22s} {data}".format(summary="TOTAL",data="blahblahblah"))
    return 0

def qaSummary(json=False):

    return 0

def quSummary(json=False):

    return 0

def qauSummary(json=False):

    printHeader(title="QoS / Account / User Job Summary")
    printTableHeader(main="QoS",submain="Account",subsubmain="User")
    Print("")
    printTotals(total_string = "{summary:22s} {data}".format(summary="TOTAL",data="blahblahblah"))
    return 0

def main():

    # Global Refs
    global DEBUG
    global CLUSTER

    parser = argparse.ArgumentParser(description="Slurm Job Queue Summary")

    # Selective entities
    parser.add_argument("-A","--account",action="append",default=[],
        help="Specify certain account only; can be used multiple times.")
    parser.add_argument("-U","--user",action="append",default=[],
        help="Specify certain user only; can be used multiple times.")
    parser.add_argument("-Q","--qos",action="append",default=[],
        help="Specify certain QoS only; can be used multiple times.")

    # Data Return Type
    parser.add_argument("-j","--json",action="store_true",default=False,
        help="Return data in json data structure. (TODO)")
    parser.add_argument("-l","--long",action="store_true",default=False,
        help="Return each job rather than a summary. Should opt for squeue with output instead.")

    # Debugging Output
    parser.add_argument("-D",dest="debug",action="count",default=0,
        help="Set a level of debugging to stderr.")

    #parser.add_argument("sp",dest="default_sp_name",default="user",nargs=1);

    # Sub-Commands
    submain = parser.add_subparsers(
        title="Heirarchy Layouts",
        description="Valid Heirarchy layouts to summarize",
        help="Heirarchy Options",
        dest="sp_name")
    sp_useronly = submain.add_parser("user",
        help="Summary of user jobs, accounts/qos not considered.")
    sp_acctonly = submain.add_parser("acct",
        help="Summary of account jobs, users/qos not considered.")
    sp_qosonly  = submain.add_parser("qos",
        help="Summary of QoS jobs, users/accounts not considered.")
    sp_acctuser = submain.add_parser("acctByUser",
        help="Heirarchy for Account/User job summary.")
    sp_qosacct  = submain.add_parser("qosByAcct",
        help="Heirarchy for QoS/Account job summary")
    sp_qosuser  = submain.add_parser("qosByUser",
        help="Heirarchy for QoS/User job summary")
    sp_full     = submain.add_parser("full",
        help="Heirarchy for Qos/Account/User job summary")
    
    #group = parser.add_mutually_exclusive_group()
    #group.add_argument('-u',action="store_true",help="Summary of user jobs, accounts/qos not considered")
    #group.add_argument('-a',action="store_true",help="Summary of account jobs, users/qos not considered")
    #group.add_argument('-q',action="store_true",help="Summary of qos jobs, users/accounts not considered")
    #group.add_argument('-au',action="store_true",help="Heirarchy for Account/User job summary")
    #group.add_argument('-qa',action="store_true",help="Heirarchy for QoS/Account job summary")
    #group.add_argument('-qu',action="store_true",help="Heirarchy for QoS/User job summary")
    #group.add_argument('-qau',action="store_true",help="Heirarchy for Qos/Account/User job summary")
    #parser.add_argument('-j',action="store_true",help="TODO: return data in json structures")
    
    # Implement a crappy,feature missing workaround for a default subparser
    # Think about redoing the class to fix this in Python < 3.3
    if 1 == len(sys.argv):
        return userSummary(json=False)

    # Run traditional parser.
    args = parser.parse_args()

    DEBUG=args.debug

    PrintDebug("debugging level set to: {debug}".format(debug=DEBUG),debug=1)

    PrintDebug(str(args),debug=1)

    slurm_config = pyslurm.config().get()
    if CLUSTER.lower() != slurm_config["cluster_name"]: 
        CLUSTER=slurm_config["cluster_name"]
    
    if args.sp_name == "user":
        return userSummary(json=args.json)

    if args.sp_name == "acct":
        return acctSummary(json=args.json)

    if args.sp_name == "qos":
        return qosSummary(json=args.json)

    if args.sp_name == "acctByUser":
        return auSummary(json=args.json)

    if args.sp_name == "qosByUser":
        return qaSummary(json=args.json)

    if args.sp_name == "qosByAcct":
        return qaSummary(json=args.json)

    if args.sp_name == "full":
        return qauSummary(json=args.json)

    return userSummary(json=args.json)

if __name__ == "__main__": main()
